#!/bin/bash

echo "🔧 Quick Setup: Production URL Configuration"
echo "=========================================="
echo ""

PRODUCTION_URL="https://healthcare-scheduler-frontend-bsu6-72jpizn4w.vercel.app"

echo "📋 STEP 1: Vercel Environment Variable"
echo "--------------------------------------"
echo ""
echo "Option A: Via Dashboard (Easiest)"
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Click your project: healthcare-scheduler-frontend-bsu6"
echo "3. Settings → Environment Variables"
echo "4. Add New:"
echo "   Name: VITE_PRODUCTION_URL"
echo "   Value: $PRODUCTION_URL"
echo "   Environment: All"
echo "5. Save and Redeploy"
echo ""
echo "Option B: Via CLI (if Vercel CLI installed)"
echo "Run these commands:"
echo "  cd frontend"
echo "  vercel env add VITE_PRODUCTION_URL production"
echo "  # Enter: $PRODUCTION_URL"
echo "  vercel --prod"
echo ""

echo "📋 STEP 2: Supabase Auth URLs"
echo "-----------------------------"
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/ljxugwfzkbjlrjwpglnx/auth/url-configuration"
echo ""
echo "2. Update Site URL:"
echo "   Change to: $PRODUCTION_URL"
echo ""
echo "3. Add Redirect URLs:"
echo "   - $PRODUCTION_URL/chat"
echo "   - $PRODUCTION_URL/admin"
echo "   - $PRODUCTION_URL/oauth/callback"
echo ""

echo "✅ After completing both steps, login will redirect to production URL!"
echo ""
